site_name: Me Neither
site_url: https://www.meneither.site

nav:
  - 主页:
      - index.md
      - 关于我: about.md
  - 课程笔记:
      - notes/index.md
      - 算法导论:
        - notes/IntroductionToAlgorithm/index.md
        - 算法基础: notes/IntroductionToAlgorithm/Fundation.md
        - 函数增长: notes/IntroductionToAlgorithm/Runtime.md
        - 分治策略: notes/IntroductionToAlgorithm/DivideAndconker.md
        - 堆排序: notes/IntroductionToAlgorithm/HeapSort.md
        - 快速排序: notes/IntroductionToAlgorithm/QuickSort.md
        - 线性时间排序: notes/IntroductionToAlgorithm/LinearTimeSort.md
        - 中位数和顺序统计量: notes/IntroductionToAlgorithm/MedianAndOrderStatistics.md
        - 红黑树: notes/IntroductionToAlgorithm/RedBlackTree.md
        - 数据结构的扩张: notes/IntroductionToAlgorithm/DataStructure.md
        - 动态规划: notes/IntroductionToAlgorithm/DynamicProgramming.md
        - 贪心算法: notes/IntroductionToAlgorithm/GreedyAlgorithm.md
        - 回溯法: notes/IntroductionToAlgorithm/Backtracking.md
      - 运筹学:
        - notes/OperationResearch/index.md
        - 线性规划: notes/OperationResearch/LinearProgramming.md
        - 单纯形法: notes/OperationResearch/SimplexMethod.md
        - 最短路径问题: notes/OperationResearch/ShortestPathProblem.md
        - 最大流问题: notes/OperationResearch/MaxFlowProblem.md
        - 运输问题: notes/OperationResearch/TransportationProblem.md
        - 对偶理论: notes/OperationResearch/DualProblem.md
        - 最优理论: notes/OperationResearch/OptimalTheory.md
        - 线搜索方法: notes/OperationResearch/LinearSearch.md
        - 梯度下降法: notes/OperationResearch/GradientDescent.md
        - 次梯度法: notes/OperationResearch/SubgradientMethod.md
        - 牛顿类算法: notes/OperationResearch/NewtonMethod.md
        - 拟牛顿法: notes/OperationResearch/QuasiNewtonMethod.md
        - 信赖域算法: notes/OperationResearch/TrustRegionMethod.md
        - 增广拉格朗日函数法: notes/OperationResearch/AugementedLagrangianMethod.md
      - 计算机网络:
        - notes/ComputingNetworks/index.md
        - 数据链路层: 
          - 概述: notes/ComputingNetworks/DataLinkLayer.md
          - 错误检测和纠正: notes/ComputingNetworks/ErrorDetectionAndCorrection.md
          - 协议: notes/ComputingNetworks/DataLinkLayerProtocol.md
        - 介质访问控制子层: 
          - 概述: notes/ComputingNetworks/MediumAccessControlSublayer.md
          - 信道分配协议: notes/ComputingNetworks/ChannelAllocationProtocol.md
          - 以太网: notes/ComputingNetworks/Ethernet.md
          - 无线局域网: notes/ComputingNetworks/WirelessLocalAreaNetwork.md
          - 网桥: notes/ComputingNetworks/Bridge.md
  - 资源分享:
      - resources/index.md
  - 博客:
      - blog/index.md
  - 照片墙:
      - photos/index.md

theme:
  language: zh
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

# plugins
plugins:
  - blog
  - search
  - glightbox

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PaPa-jun
    - icon: fontawesome/solid/envelope
      link: mailto:<pengyufenguni@mail.ustc.edu.cn>
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/id/PaPa_jun
  generator: false

copyright: Copyright &copy; 2023 - 2024 YufengPeng
repo_url: https://github.com/PaPa-jun/MeNeither
repo_name: PaPa-jun/MeNeither

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - javascripts/pseudocode.min.js
  - javascripts/pesudocode-render.js

extra_css:
  - stylesheets/font.css
  - stylesheets/pseudocode.min.css
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/katex.css
