name: ci

on:
  push:
    branches:
      - master 
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 确保获取完整历史记录

      - name: Configure Git Credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Ensure CNAME file exists in source branch
        run: |
          echo "${{ secrets.CUSTOM_DOMAIN }}" > CNAME
          git add CNAME
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Automatically update CNAME file"
            git push origin HEAD
          fi

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: pip install mkdocs-material

      - run: pip install mkdocs-glightbox

      - name: Deploy with mkdocs gh-deploy
        run: mkdocs gh-deploy --force --message "Deploying from CI [skip ci]"

      - name: Switch to gh-pages branch and ensure CNAME exists there
        run: |
          # 检查并切换到 gh-pages 分支
          git checkout gh-pages || (git checkout --orphan gh-pages && git rm -rf .)
          
          # 如果 CNAME 文件不存在，则从 master/main 分支复制过来
          if [ ! -f CNAME ]; then
            git checkout master -- CNAME
            git add CNAME
            git commit -m "Add CNAME file for custom domain"
          fi
          
          # 推送更改到 gh-pages 分支
          git push origin gh-pages